name: dev-integration-test-scheduled
on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour
jobs:
  integration-test-vault:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - name: Checkout ident
        uses: actions/checkout@v2
        with:
          repository: provideapp/ident
          path: 'ident'
          ref: dev
          token: ${{ secrets.DEPLOY_GITHUB_PAT }}             
      - name: Checkout vault
        uses: actions/checkout@v2
        with:
          path: 'vault'                      
      - run: docker-compose -f ./ops/docker-compose-integration.yml build --no-cache vault
        working-directory: vault
      - run: docker-compose -f ./ops/docker-compose-integration.yml up -d
        working-directory: vault
      - run: TAGS=integration ./ops/run_local_tests_long.sh
        working-directory: vault
      - run: docker-compose -f ./ops/docker-compose.yml logs
        working-directory: vault
      - run: docker-compose -f ./ops/docker-compose-integration.yml down
        working-directory: vault
      - run: docker volume rm ops_provide-db
        working-directory: vault                                        
      - name: slack channel update
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()  