name: Hourly Integration
on:
  schedule:
    - cron: '0 * * * *'  # every hour on the hour
jobs:
  integration-test-vault:
    runs-on: ubuntu-latest
    timeout-minutes: 10    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATION_SLACK_WEBHOOK }}
    steps:
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Checkout vault
        uses: actions/checkout@v2
        with:
          ref: dev
          path: 'vault'                      
      - run: docker-compose -f ./ops/docker-compose.yml build --no-cache vault
        working-directory: vault
      - run: docker-compose -f ./ops/docker-compose.yml up -d
        working-directory: vault
      - run: TAGS=integration ./ops/run_local_tests_long.sh
        working-directory: vault
      - name: log vault on failure
        if: failure()
        run: docker logs vault
        working-directory: vault
      - name: log ident on failure
        if: failure()        
        run: docker logs ident
        working-directory: vault                                        
      - name: Send Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
